### ISSUE TITLE
Example Project?

### ISSUE THREAD

**Issue by forsmann** [DMS-Aus/Roam#189]
It would be amazing if an example project highlighting all features exists in the test area.  I'm struggling to get this thing to do what I want.  The world would use it!

**Comment by NathanW2** [comment]
@forsmann Ben has put something together now.  Just going to check if we can post it, if so I will link it on the wiki.

**Comment by NathanW2** [comment]
@bzeeb we can post that project?

**Comment by bzeeb** [comment]
Yes definitely, all of the data is publicly available.

**Comment by NathanW2** [comment]
Ok I will update the docs and add a link

**Comment by bzeeb** [comment]
Sample projects published here for now:
http://demo.mapsolutions.com.au/RoamDemos/

Version 2.4 of Roam will automatically pick it up as an available project if you add the above URL to Settings page.
