### ISSUE TITLE
Line/Area vertex collection

### ISSUE THREAD

**Issue by PaulJupp** [DMS-Aus/Roam#204]
Ability to collect the vertices of a line or area feature like a point feature.  Logging is paused between vertices allowing straight line data capture from point to point. Utilises point averaging for improved accuracy

**Comment by NathanW2** [comment]
Isn't this the same as #203?

**Comment by bzeeb** [comment]
No, this refers to the ability to either GPS capture lines/polygons continuously (every say 1 meter / 5 seconds), or capture a vertex only when the user asks it to.

**Comment by bzeeb** [comment]
Similar to #201 but two different methods of capture, will need both.

**Comment by NathanW2** [comment]
This is done now with the Add vertex button.
