### ISSUE TITLE
QGIS offline data does not sync to database

### ISSUE THREAD

**Issue by freightTrein** [DMS-Aus/Roam#214]
The QGIS projects use a PostGIS database converted to 'offline' (sqlite copy). The edits get made and saved on the local drive fine. 

When syncing the data back to the server the data is not saved, no errors popup. If i edit in Roam, then edit in QGIS before syncing, the data edited in QGIS will sync, the Roam data will not.

**Comment by gvalenty** [comment]
Hi forsmann, can you send me the zip file too.
I have same problem.
Thanks in advance

**Comment by bzeeb** [comment]
Appears question has been resolved, closing issue.

**Comment by albertoacosta** [comment]
Hi forsmann, 
do you could send me the zip file too.
I have same problem.
aacosta1911@hotmail.com 

Thanks in advance
