### ISSUE TITLE
Auto date not working

### ISSUE THREAD

**Issue by surkul** [DMS-Aus/Roam#222]
Hi Nathan,
I have downloaded the latest version and the auto date is still not working.
I am going to attach config file and sample data for you to have a look at.
Please check and let me know what I am doing wrong.
Thanks
Appreciate your help!
Surag
Happy New Year!

**Comment by StaleNZ** [comment]
I think what you want to do is from config manager open qgis, create a new vector layer, and add a new attribute (type=date). Then use this in the config manager with Control=Date.

**Comment by bzeeb** [comment]
Hi Surkul, does your configuration look like below?

![image](https://cloud.githubusercontent.com/assets/5965006/5609408/be4093ea-94da-11e4-9471-f043fa4f4a13.png)

**Comment by surkul** [comment]
Yes, it looks like that. When I tried capturing the data in QGIS it updates the field as today's date, but not in Roam.

**Comment by surkul** [comment]
How do you add pictures etc here?

**Comment by bzeeb** [comment]
How pictures work depends a bit on what data type you are saving them out as. They may either be saved directly to a layers string field as base64 or can be saved to disk as a regular image with a file path link inserted to the _images folder in your project.

Either way, you should set up a string field in your layer which you may then set the field type to Image in the roam configuration manager.

**Comment by surkul** [comment]
No I mean on Git Hub to show what's wrong or confirm that I have the same setup. Anyways here is the download link to my project if you are keen to see the settings etc.
It is over 13mb.
https://www.wetransfer.com/downloads/014209e4d157cc223c05171f579b3f4f20150105224250/247481fb7d2c753670d2efbf2af57fce20150105224250/78d5c4

**Comment by bzeeb** [comment]
Sorry misinterpreted what you said, you can simply copy and paste the images in the git hub comment box and they should auto-upload in most browsers.

Downloaded your project and had a look, it seems that your expression doesn't work with the shapefile field type set to date.

I added a new text field and the formula works fine:

![image](https://cloud.githubusercontent.com/assets/5965006/5624853/50afeaea-95a9-11e4-8b41-f53018b2ba72.png)

![image](https://cloud.githubusercontent.com/assets/5965006/5624861/74c5cce2-95a9-11e4-9870-56cd45acc6e4.png)

Would suggest either having a simpler date expression which matches shapefile format or swapping it out to text.

**Comment by bzeeb** [comment]
As for why it works in QGIS but not in Roam I'm not sure, Nathan would need to take a look at it.

**Comment by surkul** [comment]
Thanks I will use chrome rather than IE.
Really appreciate your help in this regards.
The only reason I made that date to look like that as when I tried the way you showed in your first reply didnt work. and I thought maybe the structure of the date is not appropriate so I used that concatenated string.
So when you say "Would suggest either having a simpler date expression which matches shapefile format " - what should I do. see the screenshot below and I have changed the date field to default but I am still not getting autodate. (note: I have refreshed config, saved and done the test after changing date format to all defaults)
![image](https://cloud.githubusercontent.com/assets/8218734/5658434/cb74fc5e-9755-11e4-8b70-71da12a876e7.png)

**Comment by bzeeb** [comment]
No problem.

Changing the Edit Widget Properties in QGIS will have no effect on the actual data type of the .dbf file.

You will need to delete the column in the attributes editor then add a new one of type string:
![image](https://cloud.githubusercontent.com/assets/5965006/5658494/971976fa-973d-11e4-8013-6dd99d090860.png)

This should resolve the issues you are having with date field.

**Comment by surkul** [comment]
Ok, I will try that.
Thanks
