### ISSUE TITLE
GPS Capture 

### ISSUE THREAD

**Issue by StaleNZ** [DMS-Aus/Roam#223]
I can click GPS Capture and it saves my location. How can I also record the lat lon coordinates within the captured point so that it is visible in the point record? When I open project in QGIS I cannot find where the gps coordinate data is stored, how do I find this?

**Comment by bzeeb** [comment]
Inside the QGIS project the GPS coordinate data is somewhat hidden inside the point feature and it will be set to decimal degrees or meters depending on the coordinate system you are capturing with (set through QGIS project).

If you just need a quick way of viewing a QGIS features spatial component you may copy and paste the feature out like so:

![image](https://cloud.githubusercontent.com/assets/5965006/5608401/bbb4e81e-94bd-11e4-8c42-1d152eae0a9b.png)


If you definitely need the coordinate data visible in the attribute data you may expressions both in QGIS and Roam:

![image](https://cloud.githubusercontent.com/assets/5965006/5608408/e819f160-94bd-11e4-800b-64665ffb67da.png)

Just $x for QGIS or [%  $x  %] for Roam

![image](https://cloud.githubusercontent.com/assets/5965006/5608417/514b6d58-94be-11e4-9f37-0b53097753d4.png)

**Comment by StaleNZ** [comment]
Great thats exactly what I needed. This software looks great, will be testing it out in the field next week. Thanks.
