### ISSUE TITLE
Multiple Images 

### ISSUE THREAD

**Issue by StaleNZ** [DMS-Aus/Roam#227]
If I add two or more image widgets to the same form under different attributes the resulting images are always saved with the same filename (overwriting each other). So I end up with one image which is repeated in each widget. 

Is there a way to change the filename for each widget?

**Comment by bzeeb** [comment]
Saving images to disk is a relatively new feature, we generally save them back to a database.

Confirmed it myself it is definitely a bug that they are overwriting eachother with the same name. Will fix it up.

**Comment by NathanW2** [comment]
Now uses milliseconds for the smallest counter, if this has issues I can add a random number at the end.
