### ISSUE TITLE
List Item Access

### ISSUE THREAD

**Issue by skeenp** [DMS-Aus/Roam#229]
Would be good to see something like the following made available in listwidget.py to easily clear and add items dynamically without having to import the required libs in the form __init__.py code. Dont know if icon is needed, in my testing, icon does not seem to add value.

```python
    def clearItems(self):
        self.listmodel.clear()

    def addItem(self,data,desc):
        item = QStandardItem(desc)
        item.setData(data, Qt.UserRole)
        item.setIcon(QIcon())
        self.listmodel.appendRow(item)
	
```

**Comment by NathanW2** [comment]
You can do this to add items:

self.boundwidgets['widgetname'].config = dict(list=dict(items=liste1))

or:

self.boundwidgets["widgetname'].config['list']['items'].append("value")

**Comment by skeenp** [comment]
Cannot seem to get the list to update after appending the item using updatefromconfig but thats more likely an issue with my python coding skills :) I'll just keep using my modules above to add items dynamically with a call to:
```python 
from PyQt4.QtGui import QStandardItem
```

**Comment by NathanW2** [comment]
What does your code look like?

**Comment by skeenp** [comment]
Currently it is working as follows
```python

...
    def uisetup(self):
        self.boundwidgets['siteid'].valuechanged.connect(self.handler)
        pass

    def clearItems(self, control):
        control.listmodel.clear()

    def addItem(self, control,data,desc):
        item = QStandardItem(desc)
        item.setData(data, 32)
        control.listmodel.appendRow(item)
		
    def handler(self,value):
        self.clearItems(self.boundwidgets['type'])
        self.addItem(self.boundwidgets['type'],"ddd","Desc")
        self.addItem(self.boundwidgets['type'],"ddd 1","Desc 1")
        self.addItem(self.boundwidgets['type'],"ddd 2","Desc 2")
...
```

Using the code provided, a combination of one or more of the following lines do not add an item to the list.

```python
    def handler(self,value):
        self.boundwidgets["type"].config['list']['items'].append("value")
        self.boundwidgets["type"].config['list']['items'].append("value;data")
        self.boundwidgets["type"].updatefromconfig
```

Basically my use case for this is:
1. Combo box 1 is filled with a set of values from a CSV file on form load
2. Upon selection of item in Combo box 1, combo box 2 is cleared and then populated from a second CSV file filtered by the selection in Combo box 1. 

I've got it working using code derived from _buildfromlist in listwidget.py, just looking for an easier way without having to import additional libs into the __init__.py script when its already in the base code.

**Comment by NathanW2** [comment]
Are you calling `self.boundwidgets["type"].updatefromconfig()`

**Comment by bzeeb** [comment]
Closing question due to inactivity.
