### ISSUE TITLE
Toogle between zooms and turn on/off labels and distances

### ISSUE THREAD

**Issue by 9ls1** [DMS-Aus/Roam#231]
I find IntraMaps Roam very useful. As our use increase, our wishes increase.
In addition to **map scale** and the possibilty to **edit polyline geometry**, we would like to
1. have a **“toggle between the two last zoom levels”**-button
2. **turn off/on the labeling** of layers. I have set different labeling (sizes depending on the map scale (and here) and expression based on empty fields or not (coalesce) in QGIS, and this works perfect in Roam. However, sometimes during the capture, the user may want to turn off the labeling (labels covering the area that will be captured). Would be nice to be able to do that within Roam (or by setting it on/off in the project.config file but the latter would not be rather inconvenient compared with the first option).
3. **turn on/off the distances** when digitizing polylines? It can be quite disturbing when interpreting e.g. land cover (vegetation types) and drawing a boarder around a specific area.

**Comment by bzeeb** [comment]
1. Unlikely to implement a new button however we are have added a button which allows you to pick your zoom level from a list which may cover what you need here.

2. I like this idea, might control this from legend at some point, will think about how we could do this.

3. Agree this can get cluttered when drawing lots of points, perhaps will add as a user option/setting.

**Comment by 9ls1** [comment]
Thanks for the reply.
Regarding the "zoom level"-list, **will** it be implemented in the next version 2.4? Because I can't find it in version 2.3.1?
Looking forward to the next release, hopefully with possibilities for turning lables and distances on/off.

**Comment by NathanW2** [comment]
@9ls1 It's currently in a working branch to be merged soon. However it is a scale list not really a used zoom level list. So it will display things like 1:250, 1:500 etc to let you quickly jump between scales.

3. has also been fixed in master in ticket #235

**Comment by 9ls1** [comment]
Thanks for your comment. My mistake being unprecise in my wording. A scale list it is, and a scale list will be just fine.

**Comment by bzeeb** [comment]
We do not plan on label on/off toggle at this time, QGIS has very rich editing tools so maps should be able to be designed in such a way that they do not interfere.

Would consider adding as a sponsored development feature if required.
