### ISSUE TITLE
Issue with Roam 2.3.1 crashing

### ISSUE THREAD

**Issue by MatthewMLL** [DMS-Aus/Roam#233]
Hi

We are experiencing an issue with Roam crashing frequently since the 2.3.1 update. We're running Roam on several different tablets and are experiencing the issue on all of them.

This issue occurs frequently when the user drags or pans around the map.

The event log entry for the error is below:

Event 1000, Application Error
Faulting application name: Roam.exe, version: 2.3.1.0, time stamp: 0x53d597b7
Faulting module name: ntdll.dll, version: 6.3.9600.17278, time stamp: 0x53eeb4a3
Exception code: 0xc0000264

Any help with what could be causing our issues would be appreciated.

**Comment by bzeeb** [comment]
Hi Matthew,

This error should have been fixed in the latest developer versions if you are able to build from source, it is caused by the multi-core rendering introduced in 2.4.

Please let us know how you go, other users have reported it fixed the crashes.

**Comment by NathanW2** [comment]
@MatthewMLL are you able to build the main code base and test that?

**Comment by MatthewMLL** [comment]
Hi Nathan - sorry for the delay, was away for a few days then got a but busy with some upgrades.

Sorted out my building issues (didn't want to download py2exe.zip so manually downloaded which allowed the setupdev script to succeed. Also choose the Advanced Option when installing OSGeo4W which meant I ended up with all the packages and an error for a missing dll. Reinstalled with Express Desktop option and build succeeded.)

That aside built and have had a quick test and it looks like it has fixed the issue - have copied to two tablets for users to try and will distribute to the others tomorrow.

Thanks for the help.

**Comment by NathanW2** [comment]
Glad that has fixed the issue.  Should help on battery life as well.
