### ISSUE TITLE
 Log page to display log message

### ISSUE THREAD

**Issue by lydonchandra** [DMS-Aus/Roam#234]
We might  need a Log page to display log message from Syncing activities (or any Roam activity in general)

As of now, for SyncFramework, the log file is located at:
<ROAM executable folder>\SyncClient\logs\Log.current.log
E.g.	C:\IntraMaps Roam\SyncClient\logs\Log.current.log

Maybe we can make the log file location configurable ?

**Comment by NathanW2** [comment]
Roam already shows a log for any sync work it does.  I'm not sure we need to have it anywhere else.   Any external tools should store their logs how they see fit.
