### ISSUE TITLE
Show/Hide Attributes

### ISSUE THREAD

**Issue by Emma-D** [DMS-Aus/Roam#236]
Hi,

When I use the widget to hide attributes in QGIS, this functionality is not carried through to ROAM.  Also, the order of attributes in ROAM is quite random.  Is there a way that we force the order?

Thanks, Emma

![hidden attributes in qgis](https://cloud.githubusercontent.com/assets/8661606/6048754/7d77897c-ad17-11e4-8b35-575ad0d78ad7.jpg)

![attributes in roam not hidden](https://cloud.githubusercontent.com/assets/8661606/6048825/1844ea6c-ad18-11e4-9f05-75ff026b16f0.jpg)

**Comment by NathanW2** [comment]
Roam doesn't use the field information in the project to hide or show the
form (I'm not really a fan of that dialog in QGIS hence why I avoided it).

The order of the attributes is fixed in the latest code .

I will add something to hide fields.

- Nathan

**Comment by NathanW2** [comment]
@Emma-D I have added support for hiding fields, not via the UI yet though.  See http://roam-docs.readthedocs.org/en/latest/admin-guide/Select-Config/ for more info.  Check out the `Hiding fields` section.

**Comment by Emma-D** [comment]
You are awesome

**Comment by NathanW2** [comment]
Not sure I would go that far ;)
