### ISSUE TITLE
Imagery broken in latest dev code?

### ISSUE THREAD

**Issue by MatthewMLL** [DMS-Aus/Roam#237]
So I pulled down and built the latest code to fix a crashing issue but there might be a new issue in the latest build. 

With the same project and data files I now get "Seems like 1 layer didn't load correctly" and the 'Imagery' button is greyed out. Checking the "Missing Layers" box indicates it is the layer that was used for the 'Imagery' that worked on the current release version (2.3.1).

Admittedly we're not 100% how the Imagery button is supposed to work - our GIS person just put a raster layer in the QGIS project and it appeared to be linked to the Imagery button. 

I tried saving the project with the later version of QGIS, tried removing and re-adding the layer all to no avail. I even monitored the application with procmon and Roam seemed to be pointing at the files correctly. The file is a .ecw file if that matters (+ xml).

So at this point, either I compiled the app wrong, we're using the Imagery wrong or there is now a bug the code. (or a combination!).

Thanks
Matt

**Comment by NathanW2** [comment]
Sounds like the ECW gdal stuff isn't getting loaded right.    Can you
confirm if NCSEcw.dll and gdal_ECW_JP2ECW.dll is in roam\dist\libs

- Nathan

**Comment by MatthewMLL** [comment]
Yep - both files are in the dist\libs\ folder

Matt

**Comment by NathanW2** [comment]
I don't get that here.    The projects load ok in the version for the QGIS
version you are building against?  Make sure you load the OSGeo4W version
of QGIS to test.

**Comment by MatthewMLL** [comment]
Yep, used OSGeo4W to install (Express Desktop) so get QGIS 2.6.1 Brighton. Original projects were created under the 2.4 version, resaved project under 2.6 (warning bar in project gone), also removed the layer, saved, loaded fine in Roam, re-added layer, saved, same error.

Are you able to zip up your dev build to download and I can compare\test?

I'll grab another fresh PC and go through all the steps on that too and see what I get.

Thanks
Matt

**Comment by NathanW2** [comment]
Yep I will upload a build now.

**Comment by NathanW2** [comment]
@MatthewMLL build at https://www.dropbox.com/s/k74vvqxq3yhblk2/IntraMapsRoam.zip?dl=0

**Comment by MatthewMLL** [comment]
Thanks Nathan - that one shows the imagery. I'll do a comparison with what I'm compiling and try and work out what is happening. 

I'll close this call as its looks like it is me that is having the issue.

Thanks
Matt
