### ISSUE TITLE
need horizontal scroll bar to select data entry forms

### ISSUE THREAD

**Issue by rjwillson** [DMS-Aus/Roam#242]
First of all I just have to say that I can't believe how great IntraMaps Roam is (between it and QGIS I have almost completely replaced ArcGIS Desktop & ArcPad in my data collection workflow). Just a few more modifications to Roam will allow it to replace ArcPad for field data collection for my purposes as an ecologist.

Regarding the horizontal scroll bar request: the problem is that once one has created more than 11 forms (depending on name length) there is no way to select the ones off screen (either touch/pan or scroll with finger would work). See clip

![2015-03-23_151241](https://cloud.githubusercontent.com/assets/11098144/6788349/201cda76-d16f-11e4-963e-d63d45a320a7.png)

**Comment by NathanW2** [comment]
Would a smart grid layout work well here.  Maybe 4x or 5x?

**Comment by rjwillson** [comment]
anything that would allow the max number of forms to be used (selected from in a project). 

Roam makes it so easy to make the pick lists from a pre-defined list or layer (blew my mind how fast they could be made compared to the way I had to make them in ArcPad; probably 10x as fast).

**Comment by NathanW2** [comment]
I have made it wrap into a 5x grid at the moment. See how that goes and we can tweak it more over time.

**Comment by rjwillson** [comment]
Great, sounds like it should work. I tried to figure out how to test it but I'm a newbie when it comes to Github and unfortunately I do not have a programming background--therefore still trying to figure out how things work. Cheers.
