### ISSUE TITLE
Blue GPS marker can be hard to see on some backgrounds - is user selectable color with black crosshairs overtop possible?

### ISSUE THREAD

**Issue by rjwillson** [DMS-Aus/Roam#244]
Is user selectable color with black crosshairs and outline over top possible? The simple blue circle is often difficult to see, particularly with blue water dominating on some maps. The black crosshair with size slider in QGIS "GPS Information" tool is pretty nice but can be even better with the user-selectable colour background (sample attached)
![2015-03-23_160921](https://cloud.githubusercontent.com/assets/11098144/6789535/6359df3e-d177-11e4-8023-011fb6a16160.png)

**Comment by NathanW2** [comment]
I haven't add the option to change the colours yet however I have added a black border and cross. In the next version the maker will also change based on the type of fix:
