### ISSUE TITLE
Roam Config Manager save button hit and no save occurs

### ISSUE THREAD

**Issue by bzeeb** [DMS-Aus/Roam#246]
Seen this on three different PCs now, have to have the folder open in explorer and check the date last modified to ensure it has saved.

Seems to happen randomly after you have been working in config manager for a while, could not track down the root cause. Once the bug occurs no matter what you do to the config manager nothing saves back at form level.

Perhaps for now just add some more checking around the save function, will update if I figure out exact steps to reproduce.

**Comment by NathanW2** [comment]
I have just finished doing a refactor on most of the config manager code.  This will have to be tested again because the save logic I was using before was a bit messy.

Reopen if you see it happen again.
