### ISSUE TITLE
Editing a recently captured photo within a couple of seconds of capture crashes Roam

### ISSUE THREAD

**Issue by bzeeb** [DMS-Aus/Roam#250]
![image](https://cloud.githubusercontent.com/assets/5965006/7041067/92ec5248-de08-11e4-8543-b478ebd98951.png)

**Comment by bzeeb** [comment]
Can only do it on Surface though, suspect desktop is saving too fast while Surface is a little slower and hasn't quite finished saving when I've already hit the edit button.

**Comment by NathanW2** [comment]
I can't seem to get it crash out no matter what I do.  Can you still reproduce?

**Comment by bzeeb** [comment]
I'll test again with latest build, only got it to happen once on desktop but was very regular with tablet.

**Comment by bzeeb** [comment]
Panasonic FyßG1 same issue

**Comment by bzeeb** [comment]
Confirmed from a few sites it is occurring infrequently, requested a patch sooner rather than later.

**Comment by bzeeb** [comment]
Noted that loading the drawing pad before taking the photo means crash never occurs on any device. Based on the fact we were seeing weird interactions with removing and suddenly no crash I suspect there might be some sort of race occurring.

Current thread 0x00002530 (most recent call first):
  File "roam\editorwidgets\uifiles\drawingpad.pyc", line 78 in addMap
  File "roam\editorwidgets\uifiles\drawingpad.pyc", line 98 in showEvent
  File "roam\dataentrywidget.pyc", line 82 in add_widget
  File "roam\editorwidgets\imagewidget.pyc", line 235 in _selectDrawing
  File "roam\editorwidgets\uifiles\imagewidget.pyc", line 57 in _annotateimage
  File "roam\environ.pyc", line 61 in exec_
  File "roam\environ.pyc", line 158 in setup
  File "contextlib.pyc", line 24 in __exit__
  File "__main__.py", line 50 in <module>

Best guess is that the error occurs when the main class loads the first time

```python
class DrawingPad(Ui_DrawingWindow, QWidget):

self.resize(500, 500)

    def pixmap(self):
        return self.scribbleArea.pixmap
```

Conflicting with it trying to load the image from a photo

```python
    def pixmap(self):
        return QPixmap.fromImage(self.image)
    def pixmap(self, value):
        self.userimage = value

    def addMap(self, pixmap):
        self.painter.begin(self.image)
        self.painter.setRenderHints(QPainter.Antialiasing, True)
        self.painter.drawPixmap(QtCore.QPoint(0,0), pixmap)
        self.painter.end()
        self.update()
```

**Comment by NathanW2** [comment]
Fixed now.
