### ISSUE TITLE
Scale font size need to be reduced to be in-line with other text

### ISSUE THREAD

**Issue by bzeeb** [DMS-Aus/Roam#252]
Very noticeable on tablets which have had windows font sizes adjusted:

![image](https://cloud.githubusercontent.com/assets/5965006/7042076/89af2706-de11-11e4-9c9c-fe9726c375de.png)

**Comment by NathanW2** [comment]
This is a button so I think it makes sense to leave it larger. In fact the other font in that status bar is the wrong size and needs to be adjusted

**Comment by bzeeb** [comment]
Either way, as long as they are all the same. Just as soon as font scaling was on in windows they look very different.
