### ISSUE TITLE
Point feature terminology and icon

### ISSUE THREAD

**Issue by MATilbrook** [DMS-Aus/Roam#260]
'Digitize' instead of 'Capture' for point features - so all three points/line/polygons terminology is consistent.

Changing 'GPS Capture' icon, so as not to confuse with 'Add Vertex' icons of lines/polygons.

![image](https://cloud.githubusercontent.com/assets/9548636/7154259/b36c0f4e-e386-11e4-8a32-f9bfffc7ba32.png)

**Comment by NathanW2** [comment]
Does Digitize make sense with point though?  Doesn't feel right too me.  I think Capture or Add is fine.

**Comment by bzeeb** [comment]
Not sure why digitzing points is any different from lines or polygons? Either way you are manually recording a dot on the map.
