### ISSUE TITLE
Line and Polygon Edits

### ISSUE THREAD

**Issue by PaulJupp** [DMS-Aus/Roam#265]
Line and Polygon edits are not rendering correctly

![image](https://cloud.githubusercontent.com/assets/9345528/7176526/bf941f5c-e451-11e4-9dc6-7b0c0523b63a.png)

![image](https://cloud.githubusercontent.com/assets/9345528/7176569/027cda3e-e452-11e4-93de-746a1489f3d0.png)

**Comment by bzeeb** [comment]
The edits stay there even after capture has ended and feature is saved

**Comment by NathanW2** [comment]
I have made some changes to master that should fix this now.

**Comment by NathanW2** [comment]
@bzeeb can you test this for me.

**Comment by bzeeb** [comment]
Looks fine in latest.
