### ISSUE TITLE
Delete Option

### ISSUE THREAD

**Issue by PaulJupp** [DMS-Aus/Roam#267]
Could we get a delete option in the main tool bar when a feature is selected?

**Comment by dsmithqld** [comment]
I actually like it the way it is - on the edit form.  Maybe it could be a project option.

**Comment by bzeeb** [comment]
No reason not to keep it in both places.

**Comment by NathanW2** [comment]
@dsmithqld any reason you don't like the idea of it in the info panel?

**Comment by dsmithqld** [comment]
Little bit harder to accidentally delete but I'm fine with it on the info panel

**Comment by NathanW2** [comment]
There is a confirm dialog so it should be ok.
