### ISSUE TITLE
GPS: not active

### ISSUE THREAD

**Issue by meerestier** [DMS-Aus/Roam#271]
*GPS: not active*

I have an external GPS logger that is recognised by QGIS, but not by Roam… (Gluemax Bluetooth Loggger with Windows 8.1 on a Venue 8 tablet)

Any ideas?

**Comment by NathanW2** [comment]
That is a bit strange.   Best thing to do is grab a me a NMEA log dump when you do have a fix in QGIS so I can test with it.

**Comment by bzeeb** [comment]
Hi @meerestier  can we please get a log dump of this otherwise there is not much we can do with issue, closing for now, feel free to re-open if you are still encountering the issue.
