### ISSUE TITLE
Configmanager - Multiple Projects Select Layer Crash

### ISSUE THREAD

**Issue by dsmithqld** [DMS-Aus/Roam#274]
In the Config Manager, when there are multiple projects set up, clicking on a "select layer" in one project and then clicking on a "select layer" in another project causes a crash.

**Comment by NathanW2** [comment]
ouch

**Comment by bzeeb** [comment]
Getting this as well, found that changing layer when then preview screen is open doesn't update the preview either and can cause crash there.

**Comment by NathanW2** [comment]
Seems this is due to a layer going out of scope when the new project loads but it's a hard one to track down

**Comment by bzeeb** [comment]
This was fixed last version,
