### ISSUE TITLE
Pen-based Tablet Tolerance for Map Tools

### ISSUE THREAD

**Issue by dsmithqld** [DMS-Aus/Roam#275]
The "Select" and "Digitise" commands are almost impossible to use with a pen-based tablet as the movement tolerance appears to be 0 pixels.  Touch screen devices do not have the problem.

Some Motion F5 tablets can be switched between "touch" and "pen" mode and the problem only occurs in pen mode.

**Comment by dsmithqld** [comment]
Just noticed this occurs on "Select List" screens as well.

**Comment by NathanW2** [comment]
That commit will fix the issue with the capture tool.  The select tool should still work like normal though because when you drag with that it will make a small select rectangle so should work even with a bit of movement.

**Comment by dsmithqld** [comment]
Unfortunately, you lose the ability to "point select" an object with a pen unless you have a very steady hand and move zero pixels.  All selections must be done by dragging.  When using touch mode, you only have to touch somewhere near an object to select it which makes sense.  Maybe it's possible to set a 5-10 pixel tolerance before a "begindrag" event is triggered?
Also, the "selection list" form screens are still not usable with a pen due to zero movement tolerance.
Please re-open.
