### ISSUE TITLE
Advanced default values are lost when list config is lost

### ISSUE THREAD

**Issue by NathanW2** [DMS-Aus/Roam#276]
Seems we also drop the advanced default values when the list config is busted.  Related to #269 

Solution for this is to add UI for the advanced default config because hacking the config file is never really a fun or good idea.

**Comment by bzeeb** [comment]
Assign all the tags!

Yep hit this one a few times myself, just had to be careful not to click on those ones but would definitely support a UI for it. Maybe even have a couple of examples of which we regularly use? Like:

    expression: intersects($geometry, buffer(roam_geomvertex(0), 0.1))
    field: pit_no
    layer:
    - PitsV3

**Comment by NathanW2** [comment]
Fixed in master
