### ISSUE TITLE
Handle GLL messages

### ISSUE THREAD

**Issue by bzeeb** [DMS-Aus/Roam#280]
$GPGLL,4916.45,N,12311.12,W,225444,A,*1D

http://www.gpsinformation.org/dale/nmea.htm#GLL

**Comment by NathanW2** [comment]
Do we need to handle it or can we just ignore it for now.  I can disable logging so that it doesn't fill the log up

**Comment by NathanW2** [comment]
I have just hidden the logging for now.  Reopen if you think we need to handle the string itself.
