### ISSUE TITLE
Support "Step" parameter for numerical values

### ISSUE THREAD

**Issue by ninsbl** [DMS-Aus/Roam#289]
In QGIS one can define a "Step" parameter for the Range widget. Would be nice if Raom could do that too for numerical values. At least I did not manage to figure out how to do that with suffix and prefix if that was possible...

**Comment by NathanW2** [comment]
Step option should already be there in the UI.

On Sun, Jul 5, 2015 at 7:32 PM, Stefan Blumentrath <notifications@github.com

**Comment by ninsbl** [comment]
Hi Nathan, thanks for your swift reply.

In the Intramaps Config manager I only have:
"Minimum value", "Maximum value", "Prefix", "Suffix" and "Places" for fields with decimals, but no "Steps". See:

![roam_number_control](https://cloud.githubusercontent.com/assets/4246620/8511208/d5929a68-230d-11e5-8c74-6e13c280aa35.PNG)

Is it supposed to work with Prefix and Suffix?

**Comment by NathanW2** [comment]
Which version?

On Sun, Jul 5, 2015 at 8:08 PM, Stefan Blumentrath <notifications@github.com

**Comment by ninsbl** [comment]
Roam Version 2.4 with QGIS 2.8.1

**Comment by NathanW2** [comment]
hmm ok, maybe it's only in master at the moment.

On Sun, Jul 5, 2015 at 8:15 PM, Stefan Blumentrath <notifications@github.com

**Comment by ninsbl** [comment]
I just had a look at 
https://github.com/DMS-Aus/Roam/blob/master/src/configmanager/editorwidgets/numberwidget.py
and a "Steps" parameter does not seem to be in there..

**Comment by NathanW2** [comment]
hmm I do already support it just not in the UI it seems:

https://github.com/DMS-Aus/Roam/blob/master/src/roam/editorwidgets/numberwidget.py#L67

On Sun, Jul 5, 2015 at 8:27 PM, Stefan Blumentrath <notifications@github.com

**Comment by ninsbl** [comment]
Does that fix also support floating point precision?

**Comment by NathanW2** [comment]
Which issue?

**Comment by ninsbl** [comment]
#289
From a swift look I got the impression, that your fix only allows using integer values in the NUMBER control... Would be really useful to be able to use it for double or floating point data too...

**Comment by NathanW2** [comment]
Use Number(Double) for that. It's supported.

**Comment by ninsbl** [comment]
Ah, OK, thanks!
