### ISSUE TITLE
"Roam error" when enabling GPS

### ISSUE THREAD

**Issue by Jezza1984** [DMS-Aus/Roam#291]
Every time I enable GPS with IntraMaps Roam v2.4 following "Roam error" occurs: 

![roamerror_2](https://cloud.githubusercontent.com/assets/13348852/8697576/518af1d4-2af6-11e5-9377-2004eb0300b2.jpg)

Every second another error message with the same content is produced. The GPS location seems to be correct. 

![roamerror_3](https://cloud.githubusercontent.com/assets/13348852/8697598/ab0d3780-2af6-11e5-8ad3-645de516d26d.jpg)

Using the same device (Motion F5t) this problem does not occur with v2.3

Any idea how to fix this problem?

**Comment by Jezza1984** [comment]
Problem solved using Franson GpsGate: Establishing a virtual com port with a NMEA filter allowing only GPRMC data to pass to virtual com port seems to work just fine.

**Comment by bzeeb** [comment]
That is the workaround for now, Roam 2.4 was throwing errors on NMEA strings it does not recognize. I believe it is fixed already in the newer dev builds.

**Comment by NathanW2** [comment]
@Jezza1984 try the latest release here https://github.com/DMS-Aus/Roam/releases/tag/2.4.2
