### ISSUE TITLE
Include GPS marker on map snapshot when capturing an image

### ISSUE THREAD

**Issue by bzeeb** [DMS-Aus/Roam#298]
If GPS is active, include the marker as part of the map snapshot, perhaps make it a configurable option  here alongside xxx:

![image](https://cloud.githubusercontent.com/assets/5965006/10212732/0ae33520-6836-11e5-8ab9-db59d4117729.png)

**Comment by NathanW2** [comment]
Fixed in a6632cc300cb4d6a059d2cbb794df67c5a158d58
