### ISSUE TITLE
Option to embed datetime and coordinates on photos

### ISSUE THREAD

**Issue by bzeeb** [DMS-Aus/Roam#299]
Alongside #298, would also be useful to embed information on to photos:

![image](https://cloud.githubusercontent.com/assets/5965006/10212747/3b4e1450-6836-11e5-9b4a-31cca6cccd4b.png)

**Comment by NathanW2** [comment]
Fixed in abe08ad920faa1be276d9cc6cf31cda93dc8db5c

Each image widget can have stamp defined.  HTML and QGIS expressions are supported.

````
<style>
h1 {
  color: [% if("dia_width" > 300, 'red', 'blue') %];
}
</style>
<h1>Design Co: [% "design_co" %]</h1>
<br>
Material: [% "material" %]
</font>
```

![image](https://cloud.githubusercontent.com/assets/381660/10471103/fc802aea-7255-11e5-815a-5a860d20d74e.png)
