### ISSUE TITLE
"Crash" on Fullscreen mode

### ISSUE THREAD

**Issue by spono** [DMS-Aus/Roam#302]
I'm experiencing some issues connected to "Fullscreen mode" both on Win10 (laptop) and WinXP (Panasonic CF-U1 Tougbook).
When I select it and then pass to another tab, the buttons on the left are resized going out fron the window, in this way is impossible to deselect the option and it's needed to re-install the SW.
![winxp_fullscreen](https://cloud.githubusercontent.com/assets/14940295/10247035/394a706e-6916-11e5-9133-8f9d7c57d634.jpg)
![w10_pc_screenadapt2](https://cloud.githubusercontent.com/assets/14940295/10247036/394a9030-6916-11e5-8118-b32b9b22eb23.png)

**Comment by bzeeb** [comment]
I have seen this happen before myself, unfortunately none of the devices I have immediate access to can reproduce the issue.

**Comment by spono** [comment]
it never happened with versions previous to 2.4.2 ...I don't know if it's a sort of regression of the last one

**Comment by NathanW2** [comment]
So it's not so much a crash more that the screen doesn't resize correctly?

**Comment by bzeeb** [comment]
Yeah it isn't a crash, just the whole display goes out of whack
