### ISSUE TITLE
Bad screen adaptation

### ISSUE THREAD

**Issue by spono** [DMS-Aus/Roam#303]
Elements and font do not fit well on the screen: both on laptop (Win10) and field computer (WinXP, res. 1024x600).
Working with IMR 2.4.2 .

![w10_pc_screenadapt](https://cloud.githubusercontent.com/assets/14940295/10247115/e4fc7a88-6916-11e5-82b8-b395ec09dd4e.png)

**Comment by bzeeb** [comment]
This one I can reproduce easily, only seems to be an issue on the settings screen?

Please let me know if any other areas of the main Roam application (not config manager) are broken on low resolution displays.

**Comment by spono** [comment]
this "squeeze mode" is far more accentuated in the field computer, making the selection of the single options to become a problem.

all the rest of  tabs seem to work fine.

**Comment by PauloEduardoCardoso** [comment]
Have we any control over ROAM icons size?

When running ROAM on Tablets (1280 x 800) It would be nice to control icons size and avoid them to be hidden.

Beside that, the button to show hidden buttons is too smmal for screen tap. 

![hidden icons](https://cloud.githubusercontent.com/assets/173906/15355565/6263a6f8-1ceb-11e6-8445-449cf45e86c9.png)

**Comment by bzeeb** [comment]
If you double tap in the white space the toolbar will shrink to compact icon sizes, should work fine for that resolution.

**Comment by PauloEduardoCardoso** [comment]
Perfect!
