### ISSUE TITLE
Rapid Collection Mode

### ISSUE THREAD

**Issue by karzak** [DMS-Aus/Roam#310]
Sometimes we want to collect many points with the same information (tree points all with same species for example). It would be nice if there was an option to configure the form and then select 'Rapid Collection' which would allow users to simply plot points without the form popping back up and clicking save.

**Comment by NathanW2** [comment]
That is an interesting idea.  I had the idea for template features a while
ago this might work well with this.

**Comment by robbomatt** [comment]
I also had a user mention similar functionality the other day. The idea was for weed infestation collection. E.g. Often in a paddock there are weeds of the same type which fall under a single inspection, if you collect the first weed and fill out the form these completed attributes are then inherited by many weed geometries collected thereafter until the user chooses to stop collecting weeds of that type.

**Comment by NathanW2** [comment]
@robbomatt in the config manager have a look at the Action tab in the form builder.  There is a Save value setting which might help in this case.  You can enable it for each field and it will save the value between form sessions.   Bit of a workaround until we have full feature template support.

**Comment by bzeeb** [comment]
Sounds like this would be best build as a plugin rather than a standard feature, it shouldn't be hard to implement.

As Nathan mentioned if you set all your attributes to repeat then it would only be two taps per feature to collect out of the box.
