### ISSUE TITLE
Roam Update - IP Address instead of name causes instant fatal crash

### ISSUE THREAD

**Issue by bzeeb** [DMS-Aus/Roam#315]

**Comment by NathanW2** [comment]
I don't get a crash here at all. At least with a local IP address. 127.0.0.1:8000

**Comment by NathanW2** [comment]
Https?

**Comment by NathanW2** [comment]
Can't reproduce this at all at the moment.  It doesn't work with SSL that is a known issue but I can't fix that at the moment.  I don't get any crash at all. IP works fine if not https.

**Comment by bzeeb** [comment]
Could be https I was mixing it up with as it is working fine here

**Comment by NathanW2** [comment]
It will now report a error message to the user so at least we will now see
that.

**Comment by bzeeb** [comment]
Alright yeah I couldn't put any logs or anything in ticket as it just crashed out before even logging, should help

**Comment by bzeeb** [comment]
Testing and I believe it was the HTTPS doing it not IP address, closing as invalid
