### ISSUE TITLE
Roam does not support expression based labeling

### ISSUE THREAD

**Issue by karzak** [DMS-Aus/Roam#317]
Defining a layer's labels using the QGIS expression editor results in the labels not appearing in ROAM. Only work around I know of is creating a copy of the layer for each case, which gets cumbersome if there are more than a few.    
QGIS Label Expression   
![label_expression](https://cloud.githubusercontent.com/assets/10601061/11922634/6e17ade6-a766-11e5-934d-3a1b2cbc0e55.PNG)   
Resulting Labels in QGIS   
![qgis_labls](https://cloud.githubusercontent.com/assets/10601061/11922644/819dc490-a766-11e5-92f2-bbeb9efebd09.PNG)   
No Labels in ROAM   
![roam_no_label](https://cloud.githubusercontent.com/assets/10601061/11922649/8d2cb73a-a766-11e5-91aa-796d2bab9e41.PNG)

**Comment by NathanW2** [comment]
There is no release build of Roam against 2.12 hence why it doesn't work.
You can build it yourself against that version of you will have to wait
until I have made a release with that version.

**Comment by bzeeb** [comment]
Roam 2.5 should support this natively.
