### ISSUE TITLE
Number(Double) form controls can only save integer steps from Config Manager GUI

### ISSUE THREAD

**Issue by tmcdonel** [DMS-Aus/Roam#318]
You can change this parameter to a decimal number in the form.config file, but the field in Config Manager only allows integers, and will overwrite decimals when used the project is saved.

I tried updating src/configmanager/editorwidgets/numberwidget.py and src/configmanager/editorwidgets/uifiles/ui_numberwidget_config.ui, but this means that decimal numbers can be added for steps in integer Number controls (not sure whether this matters?).  It seems to save alright into the form.config file, but I was having trouble testing in Roam because I was getting a number of errors when trying to digitise using my compiled version of master.

**Comment by bzeeb** [comment]
We fixed this in 1cd449f8fd787c36e55de7d84ca94d58ebd27e7b
If you use dev build it should be fine
