### ISSUE TITLE
[Testing] Roam v2.4.2 - Windows 7 64-bits

### ISSUE THREAD

**Issue by jonnyforestGIS** [DMS-Aus/Roam#319]
Hi,
I create a project in QGIS 2.12.3 Lyon  and use Roam to open the project when i try to do data entry i have this error in Roam GUi:

Traceback (most recent call last):
File "roam\mainwindow.pyc", line 511, in openForm
File "roam\dataentrywidget.pyc", line 117, in load_feature_form
Attribute Error: 'None Type' object has no attirbute 'QGISLayer'

I'm using a spatialite layer and a normal shapefile and the error is the same.
Do you want the log file?

What i'm doing wrong?

Regards
João

**Comment by bzeeb** [comment]
Hi João,

This errors sounds like you have multiple form attributes bound the the same column, or an attribute bound to no column at all.

Double check through your attribute list that they all match correctly.

Regards,
Ben

**Comment by jonnyforestGIS** [comment]
I'm sorry for the late answer, the problem was that i dind't add the form. Regards
