### ISSUE TITLE
arrow symbols respect rotation value in QGIS but not in Roam

### ISSUE THREAD

**Issue by rjwillson** [DMS-Aus/Roam#321]
when using 2.4.2, I can't seem to get the symbols shown below to rotate based on a rotation field as set in QGIS. I am pretty sure this used to work in a previous version of Roam or QGIS as I had used it when collected data in the field before. See screen clips:

![settings clip](https://cloud.githubusercontent.com/assets/11098144/14797982/569084f8-0b03-11e6-9114-08725dd2f4bb.png)

as viewed in QGIS 2.14:
![qgis view](https://cloud.githubusercontent.com/assets/11098144/14798202/6ea0f1bc-0b04-11e6-9f55-1411bd6a2256.png)

as viewed in Roam 2.4.2:
![roam view](https://cloud.githubusercontent.com/assets/11098144/14798248/993601ce-0b04-11e6-8a7c-e2093a5ef1ed.png)

**Comment by bzeeb** [comment]
Which version of QGIS is saving the project file?

If you are using 2.14 I suspect it is simply the issues with going back three version as Roam 2.4.2 is on QGIS 2.8.

If you build the latest version of Roam from dev then it will be against 2.14, else wait for 2.5.

**Comment by rjwillson** [comment]
thanks @bzeeb , I am indeed using QGIS 2.14. so definitely could be the issue.

I tried to build the version of Roam following the instructions Nathan posted at http://roam-docs.readthedocs.org/en/latest/dev-guide/Building/ but could not get it to work as I detailed in https://github.com/DMS-Aus/Roam/issues/243

is there any way you can post a download link for latest version or offer advice about building from source? Just want to make my testing more meaningful by testing on latest version.

**Comment by bzeeb** [comment]
Apologies missed your response here, very late reply.

Building Roam from source is relatively straightforward, you will need the OSGeo version of QGIS installed. Downloaded a zipped copy of the Roam files from github then run run setupdev.bat:

![image](https://cloud.githubusercontent.com/assets/5965006/17389728/6aca2610-5a39-11e6-9120-2877684d7222.png)

Full instructions:
http://roam-docs.readthedocs.io/en/latest/dev-guide/Building/
