### ISSUE TITLE
Versioning or an option to backup layers

### ISSUE THREAD

**Issue by PauloEduardoCardoso** [DMS-Aus/Roam#324]
Would be possible to implement a functionality similar to that offered by QGIS [layer version plugin](https://github.com/enricofer/layerVersion) or other backup scheme?

**Comment by bzeeb** [comment]
Possibly, however this would be very easy to implement using the sync page.

Have a batch script take a copy of the data and append the current date on to the file:

```
set hour=%time:~0,2%
set min=%time:~3,2%
set secs=%time:~6,2%
set year=%date:~-4%
set month=%date:~7,2%
set day=%date:~4,2%
set datetime=%year%-%month%-%day%_%hour%-%min%-%secs%

copy "C:\Path\To\Data.file" "C:\Path\To\Data_%datetime%.file"
```

**Comment by PauloEduardoCardoso** [comment]
thank you bzeeb. could this be used to backup a sqlite file (used as spatial data container) with no issues?

**Comment by bzeeb** [comment]
I can't see any reason it would cause issues as Roam commits the changes whenever a user hits save on data entry.

**Comment by PauloEduardoCardoso** [comment]
thank you Ben. It is working just fine.
