### ISSUE TITLE
Top Item on Form Gets Cleared after Pushing Refresh in Roam Config

### ISSUE THREAD

**Issue by karzak** [DMS-Aus/Roam#325]
This is a bug I have noticed a few times and haven't seen documented here. Not the end of the world, but something users should be aware of. 

To reproduce:
1. Open roam config and go to forms. Highlight the first item in the form
2. Press 'Open in QGIS' 
3. Make a change in QGIS and save in QGIS.
4. Press 'Refresh' in roam config.
5. Save project in roam config.

The result is that the 'name' and 'field' portions of the form have been cleared. These changes carry through to the form.config file.

**Comment by bzeeb** [comment]
Confirmed, good to fix to get rid of these state errors.

**Comment by NathanW2** [comment]
@bzeeb This should now be fixed as I'm reloading the whole tree on QGIS project change.

**Comment by bzeeb** [comment]
Broken worse than before, now all of the fields get swapped to whichever was selected when you reload

**Comment by NathanW2** [comment]
@bzeeb back to you for some more testing.  Should be fixed now.

**Comment by bzeeb** [comment]
Tested, issue resolved
