### ISSUE TITLE
NameError: global name 'roam' is not defined

### ISSUE THREAD

**Issue by PauloEduardoCardoso** [DMS-Aus/Roam#326]
I'm getting a Roam Error message

> Traceback (most recent call last): 
> File "roam\mainwindow.pyc", line 331, in openkeyboard 
> File "roam\api\utils.pyc", line 41, in open_keyboard 
> NameError: global name 'roam' is not defined

when trying to use **Text** control to a String Column.

I get no Error message if I pick any other control.

**Comment by NathanW2** [comment]
I think it should be fixed but I will check.

**Comment by PauloEduardoCardoso** [comment]
Thank you Nathan

**Comment by NathanW2** [comment]
Please try this version: https://www.dropbox.com/s/svfxxycgn5xv5mm/Intramaps%20Roam.zip?dl=0

**Comment by PauloEduardoCardoso** [comment]
Nathan, the version from Dropbox is auto-changing qgislocation path (in  roam.config) to 'C:/OSGeo4W/bin/', preventing the project loading from Roam Config GUI.
This path may not be default for many users.

**Comment by bzeeb** [comment]
Tested and fine now
