### ISSUE TITLE
will ROAM correctly interact with with more recent .qgs files?

### ISSUE THREAD

**Issue by PauloEduardoCardoso** [DMS-Aus/Roam#327]
ROAM Config manager will create a 2.0 qgs file:

`qgis projectname="" version="2.0.1-Dufour"`

 QGIS 2.12 will launch a warning regarding the project version. Will Roam read properly the new, saved version, of .qgs file? Can this be an issue?

**Comment by NathanW2** [comment]
Once you save it the version will update.  I will update the template
project. I have a better way of doing this now anyway

**Comment by bzeeb** [comment]
Roam will interact practically the same way with older/newer project files as QGIS. I've only ever had issues with Styles breaking, forms themselves should be largely unaffected.

**Comment by bzeeb** [comment]
Project was updated in master I believe, also should be fine once config manager saves regardless.
