### ISSUE TITLE
Delete Feature from two-step process (ROAM 2.5.0.dev-567b71e)

### ISSUE THREAD

**Issue by PauloEduardoCardoso** [DMS-Aus/Roam#328]
**This do not apply to 2.4.2**

Delete features from a layer is now a 2-step process.

After selecting a feature (from ROAM GUI), one can only delete it after 1) choose  edit feature and then 2) delete editable feature.

2.4.2 version allows one to delete feature after selecting it (which seems to be faster and easier).

**Comment by bzeeb** [comment]
This was fixed in 2.5.2 before release, thanks.
