### ISSUE TITLE
Project update and install from shared/synced folder

### ISSUE THREAD

**Issue by PauloEduardoCardoso** [DMS-Aus/Roam#330]
Can one manage update and install from a shared folder instead of a server ? It would be useful to be able to manage client updates and installs from a synced shared folder (onedrive, dropbox, drive, other).

**Comment by NathanW2** [comment]
In roam.config you can set this option:

```
projectpaths:
 - {some path}
```

**Comment by PauloEduardoCardoso** [comment]
Yes but this is a different strategy that I need to evaluate the consequences. Can anyone share experience/ideas on strategies for sharing/updating projects?

**Comment by bzeeb** [comment]
I've successfully ran a project using a dropbox setup with the same account on multiple devices. Simply move the dropbox folder location to the Roam /projects/ folder, using junctions if needed.

The main limitation is that only one user can edit at the same time, so you will need to have a separate project for each device else Dropbox will start branching the file versions. It is still possible to have the devices reading out of each others projects however you just can't give them write access.

We had 4 connected devices this way. I would always recommend a proper merge replication/sync setup however if you want an easy to roll out solution just to get devices deployed without a web server this could be the way to go.
