### ISSUE TITLE
Project Install/Update fail publish data 

### ISSUE THREAD

**Issue by PauloEduardoCardoso** [DMS-Aus/Roam#332]
I'm not being able to publish project pack (zip) to a folder from an IIS websever. client running ROAM can read and sync projects from Demo server and from our own (when we manually put the data into the IIS server) but projects cannot be published to IIS from Config Manager.

We've setup a open folder at http://internal.bioinsight.pt/VirtualDir

It would be interesting if others could test the behaviour of ROAM when syncing from/publishing there.

**Comment by NathanW2** [comment]
Config manager can't push to the folder in the web server, it can only
write to a folder on disk so you have to run config manager on the server
or someplace that can write to the mapped drive in IIS.

I'm working on a better style for this in future

**Comment by bzeeb** [comment]
Recommend pushing to a folder which automatically FTPs contents to your server, or syncs via dropbox etc.
