### ISSUE TITLE
Form Preview (ROAM 2.5.0.dev-567b71e)

### ISSUE THREAD

**Issue by PauloEduardoCardoso** [DMS-Aus/Roam#335]
From Roam Config Manager we can jump from form to form (Project's Forms tree) and get the corresponding Details, Design and Events view.

Roam update the view for all but Form Preview. One must click Details, Design or Events and then go back to Preview to get the correct Form layout view.

**Comment by bzeeb** [comment]
It can also slightly break form configs jumps between forms like this, related to #341

**Comment by NathanW2** [comment]
Fixed in e4065b8b

**Comment by NathanW2** [comment]
The crash is still there but this ticket is related to the form preview not updating which has been fixed.

**Comment by bzeeb** [comment]
Specific issue fixed, other UI swap issues as Nathan mentioned but this one is fine
