### ISSUE TITLE
Error saving feature (ROAM 2.5.0.dev-567b71e)

### ISSUE THREAD

**Issue by PauloEduardoCardoso** [DMS-Aus/Roam#339]
What could possibly produce this error? The error message (linked image) was a single event that we were unable to reproduce.

Form is collecting points. The entire project is using a single Custom SRID. ROAM apparently fail to get a valid ROWID for the feature.

![img-20160613-wa0001](https://cloud.githubusercontent.com/assets/173906/16112074/a5288f3e-33ad-11e6-8a6e-32f06939fe44.jpg)

**Comment by paulonsampaio** [comment]
The database has a constrain to a certain SRID (coordinate system) diferent
then the one beeing use by ROAM. Put the correct srid on the qgis project
or remove the constrain on th database (maybe not a good idea)

2016-06-16 10:34 GMT+01:00 Paulo E. Cardoso <notifications@github.com>:

**Comment by PauloEduardoCardoso** [comment]
Dear Paulo Sampaio. This was a single event in a single session that was solved restarting ROAM. As I mentioned in my previous message, all layers was set to the same SRID.

Maybe an issue with multipoint geometries?

**Comment by bzeeb** [comment]
I've never seen this one myself, if it was a once off I would say it was just a rare issue with SpatialLite and safe to ignore. Let us know if it happens regularly and we can take a look, would help if you provided a sample dataset.
