### ISSUE TITLE
Editing existing point?

### ISSUE THREAD

**Issue by tristanfazio** [DMS-Aus/Roam#340]
Hi there,

Trying to edit an existing point however when I try the edit button when selecting the point it brings up a blank data entry form that requires full inputs again. Am I doing something wrong or does Roam not allow for previous points to be edited?

**Comment by PauloEduardoCardoso** [comment]
You should provide details on your project settings and Roam version. It is working just fine in 2.4.2 and 2.5.0dev-567b71e.
I'd say you may have a projection issue. Ensure that all layers uses a single SRID. reproject you vectors to the srid of your raster layer.

**Comment by bzeeb** [comment]
Happy to look at this with more info however as Paulo said this should be working fine.
