### ISSUE TITLE
Config Manager - Previews not reloading on form swap

### ISSUE THREAD

**Issue by bzeeb** [DMS-Aus/Roam#343]

**Comment by NathanW2** [comment]
@bzeeb fixed so with your for testing.

**Comment by bzeeb** [comment]
@NathanW2 tested, this particular issue fixed however now it doesn't reload when you swap from design -> preview if you have not changed your attribute selection.

For example if you hide the top field then go to the preview, it is still there unless you either swap previews or swap the selected widget first.

**Comment by NathanW2** [comment]
@bzeeb I have fixed all the widgets so they now save the active field config on any change.

**Comment by bzeeb** [comment]
Tested and working fine
