### ISSUE TITLE
Invalid literal for float (): 2,2 (ROAM 2.5.0.dev-567b71e)

### ISSUE THREAD

**Issue by PauloEduardoCardoso** [DMS-Aus/Roam#346]
First time I get this error message.

When I try to add a line from a form, I'm receiving the message bellow. The exactly same project in synced in a laptop and a tablet (both Windows 10) but the error is exclusive to the tablet (an Asus Transformer Book T100). I usually create my projects on the laptop.

Sometimes we catch something wrong with our forms while trying to preview it, but this is not the case. I can preview the form on both the tablet and the laptop and interact normally with all fields.

I have a Real Numeric (Double) field that is using the Number(Double) widget. The error disappears when I change the widget to text for example (inserting a decimal number manually from the keyboard.

Something related to Windows 10 or Python on ASUS tablet?

![roam invalid literal for float](https://cloud.githubusercontent.com/assets/173906/17784812/d36b74a2-6575-11e6-80ef-e0b66038c927.jpg)

**Comment by bzeeb** [comment]
I haven't seen this one myself anywhere, if you can provide the project with the error to try and reproduce I'm happy to take a look... am aware this is over a year old sorry.
