### ISSUE TITLE
"snapping off" not working for lines (ROAM 2.5.0.dev-567b71e)

### ISSUE THREAD

**Issue by PauloEduardoCardoso** [DMS-Aus/Roam#351]
toggle snap on/off seems to produce no effect when digitizing lines. It works as expected when using points.

**Comment by NathanW2** [comment]
Hmm strange.  Thanks.  I will take a look.

On Sat, Oct 15, 2016 at 11:03 AM, Paulo E. Cardoso <notifications@github.com

**Comment by PauloEduardoCardoso** [comment]
I could provide  you with a project if necessary.
Thanks.

**Comment by bzeeb** [comment]
Confirmed doesn't work, at least reading from an advanced digitizing settings project.

**Comment by NathanW2** [comment]
Fixed. With @bzeeb for testing.

**Comment by bzeeb** [comment]
Tested, issue resolved
