### ISSUE TITLE
Help with building Roam (Windows)

### ISSUE THREAD

**Issue by karzak** [DMS-Aus/Roam#352]
I'm trying to [build](http://roam-docs.readthedocs.io/en/latest/dev-guide/Building/) Roam on Windows and am running into the following errors:

```
Traceback (most recent call last):
  File "C:\OSGeo4W\apps\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\OSGeo4W\apps\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\OSGeo4W\apps\Python27\lib\zipfile.py", line 1520, in <module>
    main()
  File "C:\OSGeo4W\apps\Python27\lib\zipfile.py", line 1487, in main
    with ZipFile(args[1], 'r') as zf:
  File "C:\OSGeo4W\apps\Python27\lib\zipfile.py", line 766, in __init__
    self._RealGetContents()
  File "C:\OSGeo4W\apps\Python27\lib\zipfile.py", line 807, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
__main__.BadZipfile: File is not a zip file
The system cannot find the path specified.
python: can't open file 'setup.py': [Errno 2] No such file or directory
Press any key to continue . . .
```

It looks to me like setup.py is just in the wrong folder, so I changed the line in 'setupdev.bat' from 

```
setup.py install
```

to

```
..\setup.py install
```

. Correct me if I'm wrong. 

After that I run 'scripts\setupdev.bat' again and get the following error:

```
C:\OSGeo4W\apps\Python27\lib\site-packages\setuptools\dist.py:285: UserWarning:
Normalizing '2.5.0.dev' to '2.5.0.dev0'
  normalized_version,
running install
running bdist_egg
error: error in 'egg_base' option: 'src' does not exist or is not a directory
Press any key to continue . . .
```

I couldn't track down where this error was coming from (other than setup.py was not completing). Any thoughts?

**Comment by karzak** [comment]
As an aside, if someone has an already packaged Roam build against QGIS 2.12 or higher and wouldn't mind posting it somewhere, I would really appreciate it. I'm just trying to test out some of the newer Roam features as well as some of the newer QGIS features.

**Comment by NathanW2** [comment]
@karzak the latest release is 2.5 built against QGIS 2.16 https://github.com/DMS-Aus/Roam/releases/tag/v2.5

**Comment by karzak** [comment]
Wow, totally missed that. Thanks!
