### ISSUE TITLE
GPS not active

### ISSUE THREAD

**Issue by Tulshis** [DMS-Aus/Roam#353]

**Comment by bzeeb** [comment]
Hi @Tulshis , can you please expend on what the issue you are having is with the GPS?

We'll need a full description of the problem to look at it.

**Comment by Tulshis** [comment]
Hi Ben,I have received a message as below; I presume its because there is no in built gps in my device. Your suggestion is really appreciated.
Thanks.
Regards,Tulshi

 

    On Monday, 14 November 2016, 18:03, Ben Zeeb <notifications@github.com> wrote:
 

 Hi @Tulshis , can you please expend on what the issue you are having is with the GPS?We'll need a full description of the problem to look at it.—

**Comment by bzeeb** [comment]
Was an image meant to come through with that message? Might need to log on to github and paste the image directly rather than respond via email.

Regardless, your device will need an inbuilt GPS which sends data to virtual windows [COM Ports](https://en.wikipedia.org/wiki/COM_(hardware_interface))

**Comment by bzeeb** [comment]
Closing, need more info to assist.
