### ISSUE TITLE
Problem with zipfile when trying to install project from server

### ISSUE THREAD

**Issue by Struggy** [DMS-Aus/Roam#355]
First post so apologies if this has already been covered. I ran into an issue trying to install a project from the server (for the first time in 2.5.2) and I got the attached error log, I replaced the zipfile library with the version from my python27 folder and it seems to have cleared it up, no idea if the will cause other issues yet but it all seems to be working. 

[Roam.exe.log.txt](https://github.com/DMS-Aus/Roam/files/612485/Roam.exe.log.txt)

**Comment by bzeeb** [comment]
Thanks for notifying us, I haven't seen this issue myself however good to know there is a simple fix. Will keep an eye on it.
