### ISSUE TITLE
Is it possible to have automatic GPS data into a field ?

### ISSUE THREAD

**Issue by Gwen22200** [DMS-Aus/Roam#357]
Hi,

is it possible to add for a field automatic GPS value like Z, X, Y, Altitude, PDOP when we create a new point?

Thanks

**Comment by bzeeb** [comment]
Hi Gwen,

If you open the expression string builder in Roam you will see a few extra functions:

![image](https://cloud.githubusercontent.com/assets/5965006/21923525/93880306-d9af-11e6-9396-5ee95f34f53c.png)

We return some GPS info there, if this doesn't have what you need it should be very easy to tweak this file to add the extra functions you need. Full free to submit a pull request if you do add some more useful ones.

https://github.com/DMS-Aus/Roam/blob/caded2720defe18e20a308be6c62616e23742375/src/roam/qgisfunctions.py

**Comment by Gwen22200** [comment]
ok thanks,
do i need to have a precise format for the field?

**Comment by bzeeb** [comment]
The format shouldn't matter on the field, numeric or string has been fine for me in the past using $gps_z

**Comment by Gwen22200** [comment]
ok i go outside to test it ;-)

**Comment by Gwen22200** [comment]
when i want to use [%  $gps_z %] expression i have : 

Error: TypeError: 'QgsExpressionFunction' object is not callable
Traceback (most recent call last):
  File "roam\qgisfunctions.pyc", line 79, in gps_z
TypeError: 'QgsExpressionFunction' object is not callable

an idea?

**Comment by NathanW2** [comment]
On Fri, Jan 13, 2017 at 10:04 PM, Gwen22200 <notifications@github.com>
wrote:

> [% $gps_z %]


Use [% gps('z') %]

**Comment by Gwen22200** [comment]
Thanks Nathan,

i test it and everything is ok with surface pro 4 + bluetooth + GPS ALTHUS RTK
is there other values with gps(' ') like pdop...? and can you tell me if is it possible to contribute to translate intramaps into french?

Thanks a lot

Gwen
