### ISSUE TITLE
Unable to select more from more than one layer

### ISSUE THREAD

**Issue by jamespaull** [DMS-Aus/Roam#360]
Under 2.5 we are unable to select feature from more than one layer. The layer that we can select from appears to be selected at random. ie sometimes we can select roads from a roads layer, and other times we won't be able to select from this layer but will be able to select from another (ie a points layer).

**Comment by NathanW2** [comment]
What type of layer are you using?

**Comment by jamespaull** [comment]
Mapinfo tab files.

**Comment by bwragg** [comment]
I had a similar problem, all of a sudden half my layers I couldn't select features from. Not sure whats causing it in the code but I found a solution.

Open up the project.config towards the end is a "selectlayers:" section

I found that any layer I had listed below my gps_log layer I was unable to select from so I just moved it above and it started working e.g I changed this:
```
selectlayers:
- layer 1
- layer 2
- gps_log
- layer 3(not selecting)
- layer 4(not selecting)
```

to this:

```
selectlayers:
- layer 1
- layer 2
- layer 3(started being selectable)
- layer 4(started being selectable)
- gps_log
```

Not sure if its exactly your problem but it did the job for my layers (all coming out of spatialite)

**Comment by bzeeb** [comment]
Thanks for work around, I haven't been able to reproduce here. The selectlayers list can get out of whack if you change layer names in QGIS project without removing them from config manager first, closing for now as it would be resolved as part of a wider re-work of the way configs are stored.
