### ISSUE TITLE
roam.config file is being wiped again and not self repairing

### ISSUE THREAD

**Issue by bzeeb** [DMS-Aus/Roam#363]
Confirmed happening at two sites with 2.5.2, suspect it is when users shutdown tablets by holding the off button.

Fairly critical to fix as it completely blocks Roam starting and workaround is fiddly on small tablet screens (open config and enter {})

**Comment by NathanW2** [comment]
Hmm that is pretty odd too giving I have fixed it.  Will fix Friday or fix
week.
