### ISSUE TITLE
Undo Button

### ISSUE THREAD

**Issue by ChartisKathy** [DMS-Aus/Roam#364]
Roam sometimes creates a node in the middle of nowhere when selecting tools. e.g. this one is way outside of Australia (which you can see at the bottom left):

![capture](https://cloud.githubusercontent.com/assets/26241911/23643235/8afc174e-0354-11e7-9290-5ccc45c3ba6c.PNG)

Can I suggest putting in an Undo button? 

 Users can sometimes find it easier to just ignore the object and create a new object. It's quicker to do create afresh than delete the bad object or drag the bad node to the correct place.

**Comment by bzeeb** [comment]
Only just noticed this question, I have not seen Roam produce this myself. Could you explain the workflow that leads to this happening?

Does the node jump outside the view when changing tools or trying to navigate around mid capture?

**Comment by bzeeb** [comment]
@NathanW2 was this implemented into master from pull #390 ?

**Comment by NathanW2** [comment]
Yes

**Comment by bzeeb** [comment]
Nice feature @skeenp, working well
