### ISSUE TITLE
[question] How sync offline with online mode

### ISSUE THREAD

**Issue by jonnyforestGIS** [DMS-Aus/Roam#366]
Hi Nathaw, do you have an example how this works? 
http://roam-docs.readthedocs.io/en/latest/admin-guide/Syncing/

I have:
Server: Apache Server 64-bits with PostgreSQL/PostGIS+QGIS Server+ Lizmap Web Client
Field Technician: Tablet Windows 10 Pro 64-bits
Office Technician: Windows 7 64-bits

For my example is a kind of tree inspection:
The field technician geolocate, characterize the event and take a photo. Then this will sync to the office technician that will decide based on information collected. This is possible to do directly with postgis tables? (i wan to work this in offline and online mode)

Or i create a sqlite database with a folder to store the photos in the project and have a the same exactly information in postgis tables on the server with a ftp folder in the server to store the photos?
The workflow:
Field technician <->Office Technician
sqlite database store information + folder with photos linkage to the column URL of the sqlite table then
batch (e.g. with help of OGR2OGR) to sync the sqlite database with the PostgreSQL/Postgis database (when in online mode)
another batch to do a ftp sync of the folder with the photos to the server. Then Office technician can make the decision and sync back with field technician.

Regards
João

**Comment by bzeeb** [comment]
Hi João,

Out of the box we don't recommend any particular Sync workflow, it is left up to individual implementations on-site.

The documentation page you referenced is the project.config code to set up Roam with buttons pointing at windows batch scripts you must create yourself inside the project folder.

Typically you would have two buttons, one which uploads the data from the tablet -> server, then a second which downloads the data from server -> tablet, overwriting any changes.

As stated, how exactly you implement this is left up to site administrators.

Regards,
Ben

**Comment by jonnyforestGIS** [comment]
HI @bzeeb thank you for your feedback and i'm sorry for my delay.
I understand. So i need to create two batch with this type of syncing. I will try to do with ogr and ftp.

Another question is possible contribute in documentation or translation?
Regards,
João

**Comment by bzeeb** [comment]
You could place them both in the same file for upload and download, however I usually keep them separate so it is clear in the users mind what the software is doing (pushing data up to your server, or pulling down a copy).

We have translation for much of the software already however I believe there is a bug with loading the translation at the moment, hoping to get that fixed in 2.6.

For documentation if you submit a pull request to https://github.com/DMS-Aus/Roam-docs I would be happy to review and add any documentation you have put together.

**Comment by bzeeb** [comment]
https://github.com/DMS-Aus/Roam/issues/211
