### ISSUE TITLE
Search Plugin zooms too close by default

### ISSUE THREAD

**Issue by bzeeb** [DMS-Aus/Roam#367]
Search.py
Line 249

Update
        xmin, xmax, ymin, ymax = box.xMinimum(), box.xMaximum(), box.yMinimum(), box.yMaximum()
        xmin -= 5
        xmax += 5
        ymin -= 5
        ymax += 5

To
        xmin, xmax, ymin, ymax = box.xMinimum(), box.xMaximum(), box.yMinimum(), box.yMaximum()
        xmin -= 50
        xmax += 50
        ymin -= 50
        ymax += 50

**Comment by NathanW2** [comment]
Fixed in f53b871

**Comment by bzeeb** [comment]
Tested, fine now
