### ISSUE TITLE
Roam max_value function inflexible for string-based ids

### ISSUE THREAD

**Issue by ChartisKathy** [DMS-Aus/Roam#368]
The Roam max_value function currently operates expecting the name of a layer and the name of a column. If the column values are not numerical, it returns nothing.

This makes it difficult if the sole unique id is a number with a prefix/suffix. e.g. 'ID100' or 'Pipe401'. Whilst it's true that many formats offer a unique id column that is numerical e.g. OBJECTID or ogr_fid, not all do.

Could the functionality be expanded to cater for this scenario? I had expected something like this to work:

CASE
		WHEN max_value( 'Drainage Pit','ASSET_ID')  IS  null THEN 'DS100000001'
		ELSE  'DS' + to_string(max_value( 'Drainage Pit',to_int(replace(ASSET_ID,'DS',''))) + 1)
END

**Comment by NathanW2** [comment]
How do you know the max value of a string column?

If you order it will look like this:

ID100
ID1000
ID 2
ID 200
ID 2000

because that is how ordering strings works.

**Comment by ChartisKathy** [comment]
I agree that sorting strings with numbers is typically difficult and is not the default functionality, but there are programmatic solutions for these.

For example:
http://stackoverflow.com/questions/5967500/how-to-correctly-sort-a-string-with-a-number-inside
http://stackoverflow.com/questions/4836710/does-python-have-a-built-in-function-for-string-natural-sort

Even if catering for strings wasn't a out-of-the-box functionality, allowing Roam admin's to do the heavy lifting would be agreeable. However we cannot do this if the max_value function only supports a string column name rather than a programmatic derived value such as something like:
max_value('layer',to_int(replace(attribute('layer','column'),'STRING','')))

**Comment by NathanW2** [comment]
If you using more then Roam for this project and this column is your ID you
are going to get conflicts anyway which is why I don't really like
supporting max value with more logic.

ID allocation should be done server side and never client side if you are
disconnected.  We would need to be allocate ranges in Roam but can't do
that currently.

**Comment by bzeeb** [comment]
Seconding Nathans comments, best to avoid assigning IDs on client with a disconnected workflow, as soon as you add a second field inspector the entire system gets extremely messy (need to start manually setting up reserved ID blocks).

I always strongly suggest that system administrators avoid string IDs in the format such as DS1000001. There is no practical reason for them to exist in this way from a database perspective, however I am aware that most asset systems prefer this method.

Ideally assign the custom IDs on the server, or have a simple int ID field which then has the string asset ID hanging of it as a calculated field.
