### ISSUE TITLE
[question] Add icon to the Option Row

### ISSUE THREAD

**Issue by jonnyforestGIS** [DMS-Aus/Roam#369]
**System Environment:**
Roam 2.5.2.0
QGIS API: 2.16.2
Windows 7 64-bits

HI, 
i'm trying to put an icon in the option row and don't appear in the preview mode or in the project.

My steps:
add de png icon 128x128 in the folder of the form. the name of icon is check_icon.png. And in the form
i put a single line to test:
1;Good;check_icon

What i'm doing wrong?
Regards
João

**Comment by NathanW2** [comment]
On Mon, Mar 27, 2017 at 10:53 PM, João Gaspar <notifications@github.com>
wrote:

> 1;Good;check_icon


1;Good;check_icon.png

should work

**Comment by jonnyforestGIS** [comment]
Hi @NathanW2 i test with extension and have same behavior. 
I tought that maybe the size of png was the problem but i copy the default plus icon into the form folder and give the name of option row and don't work.

**Comment by bzeeb** [comment]
Hi @jonnyforestGIS , please move it up a level from the form folder to the project folder.

I tested and is working fine from \IntraMaps Roam\projects\testproject\icon.png

**Comment by jonnyforestGIS** [comment]
Thanks i try again and works fine putting at the level of the project folder and i didn't need to put the extension.

Regards
João
