### ISSUE TITLE
Select layer error

### ISSUE THREAD

**Issue by gavinere** [DMS-Aus/Roam#392]
NAthan, Any ideas on how to correct this error:

Something has gone wrong.
Error: KeyError: 'layer'
Traceback (most recent call last):
  File "roam\mainwindow.pyc", line 473, in showInfoResults
  File "roam\project.pyc", line 609, in formsforlayer
  File "roam\project.pyc", line 232, in layername
KeyError: 'layer'

[project.config.txt](https://github.com/DMS-Aus/Roam/files/1416654/project.config.txt)

**Comment by NathanW2** [comment]
What version of Roam was this in?

**Comment by gavinere** [comment]
Roam 2.5

**Comment by NathanW2** [comment]
Can you drop me the form.config file.  Looks like the form might not have a layer assigned to it for some reason. Have quick check in config manager for the form you are opening.

**Comment by gavinere** [comment]
[project.config.txt](https://github.com/DMS-Aus/Roam/files/1445070/project.config.txt)

**Comment by gavinere** [comment]
The first entry in attached looks suspicious to me.
[Roam Config Manager.exe.log](https://github.com/DMS-Aus/Roam/files/1445109/Roam.Config.Manager.exe.log)

**Comment by NathanW2** [comment]
Can you screenshot the folder C:\IntraMaps
Roam\projects\WannonWAP3\WAP_Assessment

**Comment by NathanW2** [comment]
Project config is looking for WAP_Assessment as a form folder which isn't in there.  Is it that zip file?

**Comment by gavinere** [comment]
Pretty sure this was an earlier form that I removed.  Can I just edit it out of the Project.config now?

**Comment by NathanW2** [comment]
Yep just remove it from forms: list and it will be fine. There should be a
delete form button in Config Manager which normally would do that for you.

**Comment by gavinere** [comment]
Thank.  Will try that out and see how I go.
