### ISSUE TITLE
Suddenly unable to add features???

### ISSUE THREAD

**Issue by mrmosquito12345678** [DMS-Aus/Roam#397]
So I have a project and it had been working fine and dandy, but suddenly I am unable to add any features on the project.  It goes through all the motions and then nothing appears.  Using the same layers on a new project works.  This is the second time it has happened to this project and I'm not sure how to fix this or avoid it for the future.  Things that may have triggered it as they somewhat coincided with it no longer working properly are: opening it directly in QGIS 2.18 (to use the project with QuickMapServices) rather than from Config Manager (as Web is not in the toolbar of QGIS that way); adding/editing attribute fields; adding editing Forms in Config Manager; being a doofus and maybe messing something up along the way; and also... ???  Using Windows 10 tablet with GPS, etc.

Any help would be greatly appreciated!  Thanks.

**Comment by bzeeb** [comment]
Hi, Roam is currently built against QGIS 2.16, as such it would be better to use this version to edit your project files rather than 2.18.

Give 2.16 a shot and let us know how you go.

**Comment by rjwillson** [comment]
just this week I have been running multiple projects collecting data with Roam 2.5 and the latest QGIS 2.18x. I regularly open the project files directly in 2.18 and use Quick Map Services and have had no problems. 

what you describe I have seen happen when someone has changed the CRS in the QGIS project file so that it no longer matches the data layers you are collected the data into. The CRS of the map canvas has to be the same as the data collection layers or Roam won't show the features collected. All other supporting layers that don't collect data can be other CRS

**Comment by mrmosquito12345678** [comment]
To my knowledge the CRS was not changed but overall the issue seemed to have stopped once I rolled back to an older QGIS to make changes.

But now I am having a somewhat similar issue in that I am getting an error in adding features.  It works perfectly fine until the next day.  When I try to add a point, I get the following message:

Error: KeyError: ''
Traceback (most recent call last):
  File "roam\mapwidget.pyc", line 968, in add_new_feature
  File "roam\project.pyc", line 409, in new_feature
  File "roam\project.pyc", line 440, in default_values
  File "roam\defaults.pyc", line 57, in default_values
  File "roam\defaults.pyc", line 48, in widget_default
  File "roam\defaults.pyc", line 28, in default_value
  File "roam\defaults.pyc", line 121, in layer_value
KeyError: ''

No real changes were made by me, as the tablet was shut off overnight, but it seems that much of the time when I close out I'm given various types of generic crash messages.  I have a backup of the working version of the project in the zip, but it always seems to end up giving me that message and not letting me add.`
