### ISSUE TITLE
Can't open Roam 2.6

### ISSUE THREAD

**Issue by karzak** [DMS-Aus/Roam#400]
Downloaded the latest copy (.zip) and am getting this in the log when I try to open:

I'm running win7 x64 and have no trouble with Roam 2.5

```
Traceback (most recent call last):
  File "__main__.py", line 27, in <module>
  File "contextlib.pyc", line 17, in __enter__
    Typical usage:
  File "roam\environ.pyc", line 184, in setup
    
  File "roam\environ.pyc", line 164, in _setup
    
  File "roam\environ.pyc", line 26, in init
    
  File "qgis\__init__.pyc", line 27, in <module>
    based on the position of the part in the overall string.
  File "qgis\core\__init__.pyc", line 30, in <module>
    
  File "qgis\_core.pyc", line 12, in <module>
  File "qgis\_core.pyc", line 10, in __load
ImportError: DLL load failed: The specified module could not be found.
```

![image](https://user-images.githubusercontent.com/10601061/33484185-3113a0dc-d66f-11e7-946a-6b69f408efec.png)

**Comment by NathanW2** [comment]
Hmmmm I opened and tested before I uploaded and it was ok. I will test on
Monday again.

**Comment by NathanW2** [comment]
Works here for me.  Make sure your zip file was extracted correctly and see if you still get it.

**Comment by karzak** [comment]
Working on my end now. Must have been a bad extraction or something like that. Thanks!

**Comment by NathanW2** [comment]
Hey,

Nah was an new windows DLL that needed some extra DLLs that are not Windows
8. So fixed and uploaded a new version.

What version of qgis do you have installed currently?

**Comment by karzak** [comment]
My setup is weird. I'm running osgeo4w QGIS 2.18.9 on the machine that wouldn't open Roam 2.6 earlier, but it's not installed or on the PATH variable (copy and pasted from another machine), so I'm not sure if it matters too much.

**Comment by bzeeb** [comment]
Did the new zip file on the 2.6 release work fine for you @karzak ?

**Comment by karzak** [comment]
Yes it did.
