### ISSUE TITLE
Events on option row only works on numbers (not string values)

### ISSUE THREAD

**Issue by Lendog** [DMS-Aus/Roam#406]
Events doesn't work when string is used eg
![image](https://user-images.githubusercontent.com/17174019/35955954-d736ca18-0ce6-11e8-92d7-94b10b0cb0f6.png)
...
Option row values
![image](https://user-images.githubusercontent.com/17174019/35955940-bf2257e4-0ce6-11e8-9e7e-6f3dcf654e5f.png)

no errors just doesn't work.  Also tried many different variations

but when a number is used eg below it does work
![image](https://user-images.githubusercontent.com/17174019/35955911-85c7f8be-0ce6-11e8-99f8-96a509d69355.png)

...
Option row values

![image](https://user-images.githubusercontent.com/17174019/35955924-a033b10c-0ce6-11e8-82a6-7907cfd67aaa.png)

**Comment by bzeeb** [comment]
Will investigate and confirm.

**Comment by Lendog** [comment]
Thanks for looking into it.    This issue maybe able to be closed.  For some reason it seems to be working fine now :-s         even with 'None'

I'm using this at the moment and is working as it should
![optionrow](https://user-images.githubusercontent.com/17174019/43931691-4b00d362-9c2f-11e8-938d-6d165deec07b.png)

Possibly  because its using '  '  instead of   "   "  as per original screen grab ..  although for memory I tried both.     or  possibly because this is the only event item now.  

Anyway thanks for helping :)

**Comment by Lendog** [comment]
Actually I just tested it with "None"   - doesn't work.   Tested it with 'None'  and it works.

So possibly could be my inexperience with it :)  ... sorry

Anyway thanks for the help. I might try to close the issue,  you might have just resolved it for me :)

**Comment by Lendog** [comment]
Actually any chance to get a string example in   

http://roam-docs.readthedocs.io/en/latest/admin-guide/widgetevents/

to assist others.     I can't see how to edit that page, so I'm not sure if I have the ability to do it.
