### ISSUE TITLE
Setting Layer Scale Visibility in QGIS leads to invisibility at all scales in Roam

### ISSUE THREAD

**Issue by TonyFMCMC** [DMS-Aus/Roam#409]
While setting up a project through config manager in QGIS 3, if I add a layer and use the dropdown to set the layer to only be visible up to say 1:5000, the expected behaviour happens in QGIS, but when I then open the layer in Roam and scroll in or out the layer stays invisible.

**Comment by rjwillson** [comment]
this is one of the "breaks" that happen when you open a project created in QGIS 3 with with QGIS 2.18 or earlier. The most recent version of Roam was set up to work with previous versions of Q. I think vers. 2.5 & 2.6 of Roam was compiled against QGIS 2.16 but I have used it successfully with no breaks with Q 2.18.

Three undesirable things that happen when you open a Q3 created project in 2.18 are (1) layer scale visibility settings are messed up for each layer, (2) labels turn themselves off, and (3) the CRS changes. All of these cause problems for viewing and adding data in Roam.

I use two workarounds right now: (1) you can just set up your Q project in 2.18 or (2) you can set up project in Q3 but then open it in Q 2.18, fix the above mentioned problems, and then save. Then open Roam and all should work

**Comment by TonyFMCMC** [comment]
Thanks rjwillson, I have installed Q3.  I will try installing 2.8 and update.

**Comment by TonyFMCMC** [comment]
I installed Q2.18 and this fixed the problem.  Thanks!
